### ISSUE TITLE
training code + question about prior

### ISSUE THREAD

**Issue by zoharbarzelay** [xaggi/OGNet#2]
Hi! 

Cool work, I really like how you use the old model as 'bad' examples.
It would be great if you could release the training code - it would make the repository really useful.

Also, one small question: would i be able to use the learned model (generator + discriminator) as a prior, when i train a reconstruction network? i mean:
phase 1: learn a prior over reconstructions
phase 2: use the prior during optimization (without changing the prior)

Thanks!
Z.

**Comment by xaggi** [comment]
Hello!
Due to some restrictions, we are unable to release the code of an ongoing project at this moment. However, we are trying to get around this. Soon after this is resolved, I will upload the rest of the code.

About the question, the G in a G + D model is already a reconstruction network. Could you please elaborate the question further?

**Comment by xaggi** [comment]
Hello!

Thank you for liking our work. :)
Due to some restrictions, we are unable to release the code of an ongoing project at this moment. However, we are trying to get around this. Soon after this is resolved, I will upload the rest of the code.

About the question, the G in a G + D model is already a reconstruction network. Could you please elaborate the question further?
