### ISSUE TITLE
The time when the whole study ends.

### ISSUE THREAD

**Issue by RohDonghyeon** [xaggi/OGNet#4]
Thanks for providing good code.

I am currently training, but it seems to be taking too long.

I am wondering if it takes a long time or will it stop if the result is okay to some extent in the middle.

If you had to run all epochs 100 (100 iterations for each epoch), how long did it take to learn?

**Comment by xaggi** [comment]
Hi,
Sorry for the delay in my response. I have been very busy lately. 
The training epochs in phase one and the training iterations in phase two are needed to be set based on the dataset you are training. In the code provided, these values are set to high numbers so that the difference in performance stability with the baseline can be easily observed. If you are training on a smaller dataset, say MNIST, less than 10 epochs are sufficient to observe this behavior.
